### ISSUE TITLE
is there any easy way to convert this code into genshin and hi3 check ins?

### ISSUE THREAD

**Issue by ejtack1** [torikushiii/starrail-auto#12]
I really like how simple and easy this is and the integration with discord and I was wondering if editing some things in the script would be easy enough for me (not very tech-y) to do or—

**Comment by torikushiii** [comment]
Should be fairly easy if you want to migrate this into Genshin not sure about HI3.

The only requirement that you need to do is change the check-in base URL from HSR to Genshin and replace the `act_id` to Genshin `act_id e202102251931481` because I'm pretty sure the response structure is almost identical.

If you need help, feel free to ask here.

**Comment by nhquyetdev** [comment]
yes, try getting its api, i don't play HI3 so i didn't have it
![image](https://github.com/torikushiii/starrail-auto/assets/118709282/31204e2c-112b-41ee-840f-07ca692475ca)

**Comment by torikushiii** [comment]
HI3 act_id: `e202110291205111`

-  Award list URL:
https://sg-public-api.hoyolab.com/event/mani/home?lang=en-us&act_id=e202110291205111

- URL for to check wether you're already checked in for today or not:
https://sg-public-api.hoyolab.com/event/mani/info?lang=en-us&act_id=e202110291205111

- Check-in URL:
https://sg-public-api.hoyolab.com/event/mani/sign?lang=en-us # POST

Here's a list of URL that you'll need to work around HI3.

**Comment by ejtack1** [comment]
tysm!

**Comment by ejtack1** [comment]
so good news! the genshin change worked + i've made modifications on the appearance of the discord webhook + hi3 seems to work the same way!
