### ISSUE TITLE
webhook still send stamina info even when check stamiona is set to false

### ISSUE THREAD

**Issue by Harrysdog** [torikushiii/starrail-auto#40]
at title said, i did not notice that i set the setting to false so when the check stamina notification start anoying me i go into config.json to switch it to false to only found out its already false, also it double send the stamina notification,
![Image 406](https://github.com/torikushiii/starrail-auto/assets/135253560/e6e7e884-4a02-4eec-86d0-0f0dcf605962)
![Image 405](https://github.com/torikushiii/starrail-auto/assets/135253560/4b246275-7666-4d16-a8f4-5a4ea0d5191a)

(unrelated to title, is there a way to change the time for check in from 12 am to 4 am?)

**Comment by torikushiii** [comment]
I've pushed a new commit that fixes that issue, and for the check-in time you can look for `CHECK_IN` in your `default.config.json` or `config.json` that will look like this: https://github.com/torikushiii/starrail-auto/blob/6a02448616f192abfedbf67273ff339c7afacc7f/default.config.json#L57

and change into `0 0 4 * * *`

**Comment by Harrysdog** [comment]
title issue have been solve so i will be closing this

**Comment by Harrysdog** [comment]
> I've pushed a new commit that fixes that issue, and for the check-in time you can look for `CHECK_IN` in your `default.config.json` or `config.json` that will look like this:
> 
> https://github.com/torikushiii/starrail-auto/blob/6a02448616f192abfedbf67273ff339c7afacc7f/default.config.json#L57
> 
> and change into `0 0 4 * * *`

for some reason, webhook keep pushing check in at 1 am and push again at 4 am (time that set to change to)

im not going to reopen this as this unrelated to title and prefer you fix it when you got free lots of time, but would open new issue ticket on April next week
![Image 411](https://github.com/torikushiii/starrail-auto/assets/135253560/b1422e3e-34c6-4e44-b890-1c8a214f13e4)
![Image 413](https://github.com/torikushiii/starrail-auto/assets/135253560/bc3a1b1c-73ec-448a-9a78-3f8611b07ddd)

**Comment by torikushiii** [comment]
i will take a look later around this day and see what's wrong with it, thank you for reporting it!

**Comment by torikushiii** [comment]
The reason it does this is because the cron job https://github.com/torikushiii/starrail-auto/blob/master/crons/check-in-checker/index.js keeps checking every hour to see if there was a missed daily check-in by the program. https://github.com/torikushiii/starrail-auto/blob/6a02448616f192abfedbf67273ff339c7afacc7f/crons/check-in-checker/index.js#L3

I've pushed a new commit and added a new option to disable this behavior completely. You can find the option at the updated `default.config.json` and look for this https://github.com/torikushiii/starrail-auto/blob/1fe061a42513cfba0365c98de0420c1a3751521a/default.config.json#L60

I could not think any better way to implement this properly at the moment.

**Comment by Harrysdog** [comment]
ok thank you
