### ISSUE TITLE
StarRailError: Account 1 is invalid.

### ISSUE THREAD

**Issue by gwendolynemaxinegwenstacy** [torikushiii/starrail-auto#45]
"request":{"statusCode":200,"body":{"data":null,"message":"Please login","retcode":10001}}}
I've try to logout and login again but nothing have change. What should i do?

![image](https://github.com/torikushiii/starrail-auto/assets/62282146/981fbb8c-ff0a-4e68-8c24-75c6a26b3e71)
![image](https://github.com/torikushiii/starrail-auto/assets/62282146/12c893b4-7bde-40b2-aecb-9aa7cb81cb10)
![image](https://github.com/torikushiii/starrail-auto/assets/62282146/1331df46-c5a1-4c15-b2d5-f5bc7cfcd198)

**Comment by torikushiii** [comment]
Can you repeat the getting cookie step, but instead of going to the network tab, go to:
1. Application tab
![image](https://github.com/torikushiii/starrail-auto/assets/21153445/b7b9d211-beda-4c54-98b8-e293b6f130a8)

2. And look for `Storage` tab at the left column, then look for Cookies > https://www.hoyolab.com
![image](https://github.com/torikushiii/starrail-auto/assets/21153445/a67fe81c-1945-49c2-9d0f-fa971f22a904)

3. Then look for all the required cookies which is  `account_mid_v2, cookie_token_v2, and ltuid_v2` at the Filter box
> [!NOTE]
> For the `cookie_token_v2` look for the bigger size one

![image](https://github.com/torikushiii/starrail-auto/assets/21153445/692447ab-0925-4a27-8861-6c10c5410520)

4. After that copy the token at the very bottom box
![image](https://github.com/torikushiii/starrail-auto/assets/21153445/a24060a5-7195-4a3e-866f-9f2be17d3c8b)

repeat this for every required cookies

**Comment by gwendolynemaxinegwenstacy** [comment]
Thank you, it worked, i noicted that the "cookie_token_v2" is much longer, for size both of them is the same. I got it running.
![image](https://github.com/torikushiii/starrail-auto/assets/62282146/d946bde4-37b9-4668-9737-19a52792fded)

**Comment by gwendolynemaxinegwenstacy** [comment]
Also, you need to logout and login again on hoyolab website to refresh a new cookie_token_v2 (If you follow the correct guide above but still get "message":"Please login","retcode":10001}}}) <- relog and get a new cookie_token_v2 fix this for me.

**Comment by torikushiii** [comment]
So, I'm assuming this issue has been fixed? If it does I will close the issue

**Comment by gwendolynemaxinegwenstacy** [comment]
Yes!
